# Generated by Django 4.1.7 on 2023-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="note",
            field=models.CharField(default="", max_length=200),
        ),
    ]
