# Generated by Django 4.1.7 on 2023-03-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_image_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="note",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
