# Generated by Django 4.1.7 on 2023-03-06 07:17

from django.db import migrations, models
import myapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_image_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="photo",
            field=models.FileField(
                upload_to="myimage",
                validators=[myapp.validators.validate_file_extension],
            ),
        ),
    ]
