# Generated by Django 4.1.7 on 2023-03-06 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_image_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="photo",
            field=models.FileField(
                upload_to="myimage",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "mp4", "ico"]
                    )
                ],
            ),
        ),
    ]
